---
- hosts: all
  pre_tasks:
    - name: "installing testing packages"
      action: package
              name=wget,net-tools
              state=installed
      when: ansible_os_family == 'Debian'
  roles:
    - role: unifi-controller
