---
# Include variable definitions
- name: "include variable overrides"
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/{{ ansible_os_family }}.yml"
  tags:
    - unifi-controller

# Install repository
- name: Install ubnt apt repository
  apt_repository: >
    filename="{{ unifi_controller_apt_repo_filename }}"
    repo="{{ unifi_controller_apt_repo_url }}"
    state="{{ unifi_controller_apt_repo_state }}"
  when: ansible_os_family == "Debian"

# Install repository key
- name: Install ubnt apt key
  apt_key: >
    keyserver="{{ unifi_controller_apt_key_server }}"
    id="{{ unifi_controller_apt_key_id }}"
  when: ansible_os_family == "Debian"

# Install packages
- name: install unifi-controller packages
  package: >
    allow_unauthenticated=yes
    name="{{ unifi_controller_packages }}"
    state="{{ unifi_controller_packages_state }}"
  become: yes
  tags:
    - unifi-controller

# Manage service
- name: manage unifi-controller services
  service: >
    name="{{ unifi_controller_service_name }}"
    state="{{ unifi_controller_service_status }}"
  become: yes
  when: unifi-controller_service_name is defined
  tags:
    - unifi-controller
    - unifi-controller_service
  notify:
    - restart unifi-controller
