# vim: ts=2 sw=2 et :
---
# Include variable definitions
- name: "include variable overrides"
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/{{ ansible_os_family }}.yml"
  tags:
    - unifi

# Install repository
- name: install ubnt apt repository
  apt_repository:
    filename: "{{ unifi.repo.name }}"
    repo: "{{ unifi.repo.url }}"
    state: "{{ unifi.repo.state }}"
  become: yes
  when: ansible_os_family == "Debian"
  tags:
    - unifi

# Install repository key
- name: install ubnt apt key
  apt_key:
    keyserver: "{{ unifi.repo.key.server }}"
    id: "{{ unifi.repo.key.id }}"
  become: yes
  when: ansible_os_family == "Debian"
  tags:
    - unifi

# Install java packages
- name: install java packages
  apt:
    allow_unauthenticated: yes
    name: "{{ item }}"
    state: "{{ unifi.package.state }}"
    update_cache: yes
  with_items: "{{ unifi.java.package.names }}"
  become: yes
  when: test is undefined
  tags:
    - unifi
  notify:
    - restart unifi

# Install packages
- name: install unifi-controller packages
  apt:
    allow_unauthenticated: yes
    name: "{{ item }}"
    state: "{{ unifi.package.state }}"
    update_cache: yes
  with_items: "{{ unifi.package.names }}"
  become: yes
  tags:
    - unifi
  notify:
    - restart unifi

# Update unifi snappy java
- name: update unifi-controller snappy java
  get_url:
    url: "{{ unifi.java.snappy.url }}"
    checksum: "{{ unifi.java.snappy.checksum }}"
    dest: "{{ unifi.java.snappy.file }}"
  become: yes
  tags:
    - unifi
  notify:
    - restart unifi

- name: disable mongodb default instance
  lineinfile:
    path: '{{ unifi.mongodb.config.file }}'
    regexp: '^ENABLE_MONGODB='
    line: 'ENABLE_MONGODB=no'
  become: yes
  tags:
    - unifi
  notify:
    - restart mongodb

- name: configure java for unifi
  lineinfile:
    create: yes
    path: '{{ unifi.config.file }}'
    regexp: '^JAVA_HOME='
    line: 'JAVA_HOME={{ unifi.java.home }}'
  become: yes
  tags:
    - unifi
  notify:
    - restart unifi

- name: manage unifi-controller services
  service:
    name: "{{ item }}"
    state: "{{ unifi.service.state }}"
  with_items: "{{ unifi.service.names }}"
  become: yes
  when: unifi.service.names is defined
  tags:
    - unifi
