---
- name: include variable overrides
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "vars/{{ ansible_distribution }}.yml"
        - "vars/{{ ansible_os_family }}.yml"
      skip: true
  tags:
    - unifi

- name: install gpg
  apt:
    name: gnupg
    state: present
  become: yes
  when: ansible_os_family == "Debian"
  tags:
    - unifi

- name: install ubnt apt key
  apt_key:
    keyserver: "{{ unifi.repo.key.server }}"
    id: "{{ unifi.repo.key.id }}"
  become: yes
  when: ansible_os_family == "Debian"
  tags:
    - unifi

- name: install ubnt apt repository
  apt_repository:
    filename: "{{ unifi.repo.name }}"
    repo: "{{ unifi.repo.url }}"
    state: "{{ unifi.repo.state }}"
  become: yes
  when: ansible_os_family == "Debian"
  tags:
    - unifi

- name: install java packages
  apt:
    allow_unauthenticated: yes
    name: "{{ unifi.java.package.name }}"
    state: "{{ unifi.java.package.state }}"
    update_cache: yes
  become: yes
  when: ansible_architecture == "armv7l"
  tags:
    - unifi
  notify:
    - restart unifi

- name: install unifi-controller packages
  apt:
    allow_unauthenticated: yes
    name: "{{ item }}"
    state: "{{ unifi.package.state }}"
    update_cache: yes
  with_items: "{{ unifi.package.name }}"
  become: yes
  tags:
    - unifi
  notify:
    - restart unifi

- name: update snappy java
  get_url:
    url: "{{ unifi.java.snappy.url }}"
    checksum: "{{ unifi.java.snappy.checksum }}"
    dest: "{{ unifi.java.snappy.file }}"
  become: yes
  tags:
    - unifi
  notify:
    - restart unifi

- name: disable mongodb default instance
  lineinfile:
    path: '{{ unifi.mongodb.config.file }}'
    regexp: '^ENABLE_MONGODB='
    line: 'ENABLE_MONGODB=no'
  become: yes
  tags:
    - unifi
  notify:
    - restart mongodb

- name: configure java for unifi
  lineinfile:
    create: yes
    path: '{{ unifi.config.file }}'
    regexp: '^JAVA_HOME='
    line: 'JAVA_HOME={{ unifi.java.home }}'
  become: yes
  tags:
    - unifi
  notify:
    - restart unifi

- name: manage services
  service:
    name: "{{ unifi.service.name }}"
    state: "{{ unifi.service.state }}"
    enabled: "{{ unifi.service.enabled }}"
  become: yes
  tags:
    - unifi
